rockdaboot/wget2

- src/options.c
- src/options.h
- src/wget.c
I'm creating a pull request here since I'd like to ask for a review before actually merging this code.
The patches are simple. They do three important things:
1. Add a utils.[ch] file for defining commonly used functions.
2. Rename the --num-threads option to --max-threads. Since, we're really defining the "max" value here.
3. Use the config.num_threads variable to store the actual number of threads that the instance will use.
Here, I'm not sure if I've missed something that actually needs to use the config.max_threads option but isn't. @rockdaboot if I'm missing something, please point out.
Should fix #9
> Ensure that Wget2 does not spawn more threads than needed

- src/options.c
- src/options.h
Currently the ocsp and hsts files are being created in the $PWD. Instead initialize them to point to a constant location in $HOME.
Will close #14
> OCSP and HSTS files should be stored to ~/.wget_*

- src/options.c
- src/wget.c
I'm not too happy with this commit since it makes the code look ugly. But I quickly made it up to silence Clang complaining about an unused return value from a function which explicitly asks for the return value to be checked.
> Check asprintf return

- include/libwget.h
- libwget/hsts.c
- libwget/iri.c
- src/wget.c
I don't know if I'm missing something, but from my tests, HSTS policies didn't seem to be applied.
Before the patch (latest git):
```
$ src/wget2 --delete-after http://www.airbnb.es
[0] Downloading 'http://www.airbnb.es' ...
HTTP response 301 Moved Permanently
[0] Downloading 'https://www.airbnb.es/' ...
WARNING: OCSP is not available in this version of GnuTLS.
HTTP response 200 OK
```
After the patch:
```
$ src/wget2 --delete-after http://www.airbnb.es
[0] Downloading 'http://www.airbnb.es' ...
HSTS in effect for www.airbnb.es:80
WARNING: OCSP is not available in this version of GnuTLS.
HTTP response 200 OK
```
I've effectively checked how after my patch, the website was loaded directly through HTTPS.
All the tests were performed with an already existing `~/.wget_hsts` for …
> Fixed HSTS policy application

- src/options.c
- src/options.h
- src/wget.c
* src/options.h (struct config): Define follow_metalink.
* src/options.c (print_help): Add description for follow-metalink.
(struct options): Add follow-metalink.
(struct config): Initialize follow_metalink.
* src/wget.c (downloader_thread): Skip following metalinks when follow_metalink is off.
(_get_header): Store the metalink file when follow_metalink is false.
> wget: new option --follow-metalink

- docs/wget2_manual.md
- src/wget.c
- tests/test-wget-1.c
This set of commits fixes a regression in the behaviour of Wget2.
Wget 1.x has for a long time supported using -c and -O options together in an undocumented manner. This behaviour is now both accepted and expected behaviour. Hence, update how Wget2 handles such a corner case.
The documentation for Wget2 has also been updated to reflect the fact that Wget2 will not consider -O to be merely a shell redirection. This "feature" of Wget 1.x has in the past caused plenty of confusion and should be simply avoided. Instead, the behaviour of -O in Wget2 will be explicitly documented.
> Fix issue with --continue and -O are passed together

- src/wget.c
When using HTTP/2 with basic authentication, the event loop sets jobs to NULL before processing the 401 Unauthorized response. This causes us to dereference a NULL pointer which causes a segfault. 
* src/wget.c(downloader_thread): Ensure job exists before trying to dereference it
> Fix segfault in case of Basic Authentication with HTTP2

- libwget/cookie.c
- libwget/encoding.c
- libwget/hsts.c
- libwget/netrc.c
- libwget/ocsp.c
- libwget/tls_session.c
* libwget/cookie.c (_compare_cookie{,2}): Mark as pure
* libwget/encoding.c (_utf8_is_valid): Same
* libwget/hsts.c (_compare_hsts): Same
* libwget/ocsp.c (_compare_ocsp): Same
* libwget/netrc.c (_compare_netrc): Same
* libwget/tls_session.c (_compare_tls_session): Same
> Mark some functions as pure

- .travis.sh
- .travis.yml
- .travis_setup.sh
- Makefile.am
- tests/libtest.c
- tests/valgrind-suppressions
* .travis.sh: Rewrite for clarity and speed. Testing shows that valgrind
and ASan don't play well together. So split their executions.
* .travis.yml: Enable ccache for builds. Also try to update libc6 if
possible
* .travis.yml: Do not run on OSX with CC=gcc. This is because on OSX,
gcc is only a wrapper around clang.
* .travis_setup.sh: Cosmetic changes only
* Makefile.am (check-coverage): Explcicitly disable valgrind tests when
checking coverage
* tests/libtest.c (wget_test): Use a provided suppressions file for
valgrind. This is required since the valgrind version on Travis seems to
be out of sync with libc. This causes valgrind to report a memory bug
falsely.
* tests/valgrind-suppressions: New file with some valgrind suppressions.
Included suppressions are for a valgrind/libc bug and …
> Improved testing on Travis

- src/options.c
- src/wget.c
- src/wget_options.h
- tests/test-wget-1.c
* src/options.c: Add new --header option and a new parse_header()
parsing function for that
* src/wget_options.h: Same
* src/wget.c (http_create_request): Add the user added headers to the
HTTP Request
* src/test-wget-1.c: Add a test for the --header option
> Support --header option

- include/wget/wget.h
- libwget/iri.c
- src/job.c
- src/wget.c
- tests/libtest.h
This pull request aims to migrate from using the following form for exporting symbols:
```
void
wget_millisleep(int ms) LIBWGET_EXPORT;
```
to this form:
```
WGETAPI void
wget_millisleep(int ms);
```
Here, the attribute for exporting a library symbol now appears *before* the function prototype. Also, the macro for exporting is changed to `WGETAPI` which is more readable and in-line with various other libraries.
Once merged, this should close #122
> Migrate from LIBWGET_EXPORT to WGETAPI

- libwget/cookie.c
- libwget/hpkp.c
- libwget/hsts.c
- libwget/ocsp.c
- libwget/tls_session.c
* libwget/cookie.c: Write time_t as long long int
* libwget/hsts.c:   Likewise
* libwget/ocsp.c:   Likewise
* libwget/tls_session.c: Likewise
* libwget/hpkp.c:   Read and write time_t as long long int
Reported-By: Tim Rühsen
This fixes #146
> Read and write time_t as long long int

- tests/Makefile.am
- tests/libtest.c
When build tree is different from source tree, libtest.la is not able to find suppressions file because it is looking in the build tree where the file is not there.
> Fix path of valgrind-suppressions for separate build tree

- libwget/http.c
When two pointers are subtracted, the resultant is a signed integer `ptrdiff_t`  which might not be able to hold the resultant value. That is what is happening in bug #158.
This fixes bug #158.
> * libwget/http.c: Avoid signed integer overflow due to intermediate ptrdiff_t by casting operands to uintptr_t

- .gitmodules
Since most proxy/fire-walled environments block remote port 9418 which is used by `git://` protocol, use `https://` instead. This supports all the users including non-proxy environments.
> Use https:// instead of git://

- include/wget/wget.h
* include/wget/wget.h : Use time_t instead of long
Reported-by : Gisle Vanem
> Use time_t instead of long

- configure.ac
* configure.ac: Check for valgrind and Sanitizers being mutually exclusive
* configure.ac: Make ./configure --help document above check
* configure.ac: Make ./configure --help document the existing check of asan and msan
This fixes #165
> * configure.ac: Check for Valgrind and Sanitizers being mutually exclusive

- configure.ac
* configure.ac: Fix test for asan and tsan being mutually exclusive
* configure.ac: Make `./configure --help` document about msan and tsan being mutually exclusive
This fixes the existing test for Address sanitizer and Thread sanitizer being mutually exclusive.
> * configure.ac: Fix test for asan and tsan being mutually exclusive

- src/options.c
Still not sure why do we need to show `"ssl/gnutls"` when we are already showing `"https"`.
> * src/options.c (print_version): Remove redundant preprocessor check

- docs/wget2.md
- libwget/http.c
- src/options.c
- src/wget.c
- src/wget_options.h
* docs/wget2.md: Likewise
* libwget/http.c: Likewise
* src/options.c: Likewise
* src/wget.c: Likewise
* src/wget_options.h: Likewise
Needed for backward compatibility with Wget 1.x.
> Rename --retry-on-http-status to --retry-on-http-error

- include/wget/wget.h
- libwget/http_highlevel.c
- libwget/ssl_openssl.c
Potential fix for #344.
In the `openssl` `tls` provider, `debug_skip_body` isn't being set on OCSP requests, which have binary bodies. This results in debug output printing binary output, which can be weird depending on terminal settings.
Example of debug output before fix (notice unprintable characters in the body):
```
16.151640.473 opened connection ocsp.sectigo.com
16.151640.473 # sent 264 bytes:
POST / HTTP/1.1
Host: ocsp.sectigo.com
Accept-Encoding: identity
Accept: */*
Content-Type: application/ocsp-request
Content-Length: 120
0v0t0M0K0I0	+
16.151640.473 ### req 0x79f04c1c3ad0 pending requests = 1
```
Example with fix (notice the `<body skipped>`):
```
16.153227.955 opened connection ocsp.sectigo.com
16.153227.955 # sent 264 bytes:
POST / HTTP/1.1
Host: ocsp.sectigo.com …
```
> set debug_skip_body for OCSP requests in openssl tls provider
